name: Update syukujitsu.json

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run script
        run: uv run main.py
      - name: Generate ISO 8601 timestamp
        id: timestamp
        run: echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
      - name: Prepare artifact directory
        run: |
          mkdir dist
          mv syukujitsu.json dist/
      - name: Push to artifact branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: artifact
          publish_dir: ./dist
          commit_message: "Update: ${{ steps.timestamp.outputs.time }}"