name: Update syukujitsu.json

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run script
        run: uv run main.py
      - name: Generate ISO 8601 timestamp
        id: timestamp
        run: echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
      - name: Prepare artifact directory
        run: |
          mkdir dist
          mv syukujitsu.json dist/
      - name: Deploy to artifact branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin artifact || echo "Branch artifact not found, will create it."
          git checkout artifact || git checkout --orphan artifact
          git rm -rf . || true
          cp dist/syukujitsu.json ./
          git add syukujitsu.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update: ${{ steps.timestamp.outputs.time }}"
          git push origin HEAD:artifact